name: harpy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - opencv
  - pip
  - rasterio
  - pip:
      - torch
      - cellpose
      - rioxarray
      - squidpy
      - spatialdata
      - spatialdata-plot
      - distributed
      - bokeh
      - ipython
      - ipykernel
