name: napari-spongepy
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.9.1
  - pytorch=1.12
  # add for  CUDA GPUs
  # - cudatoolkit=11.3
  - napari=0.4.16
  - pandas==1.4.2
  - numpy==1.21.6
  - scikit-image==0.19.2
  - seaborn==0.11.2
  - matplotlib==3.5.2
  - scipy==1.8.0
  - jupyterlab==3.4.0
  - ipywidgets==7.7.0
  - anndata==0.8.0
  - tqdm==4.64.0
  - modestimage==0.2
  - widgetsnbextension==3.6.0
  # polygons
  - geopandas
  - rasterio
  - shapely
  # scanpy
  - scanpy==1.9.1
  - python-igraph
  - leidenalg
  # dev tools
  - pre-commit
  - pytest
  - tox
  - mypy
  - pip
  - pip:
    - squidpy==1.2.0
    - opencv-python-headless
    - cellpose==2.0.5
    - basicpy==1.0.0
    - nbmake==1.3.4
    - pytest-xdist==2.5.0
