"""Canonical label-instance centers and their persisted table contract."""

from harpy.table.canonical_centers._calculation import (
    calculate_canonical_centers,
    read_canonical_centers_from_cache,
)
from harpy.table.canonical_centers._models import (
    CanonicalCacheMismatch,
    CanonicalCacheReport,
    CanonicalCacheState,
    CanonicalCacheUpdateAction,
    CanonicalCacheUpdatePayload,
    CanonicalCacheUpdateResult,
    CanonicalCentersResult,
    CanonicalMetadata,
    CanonicalMismatchCode,
    CanonicalRegionBinding,
    CanonicalRegionMetadata,
    CanonicalSourceSignature,
    build_instance_set_digest,
)
from harpy.table.canonical_centers._schema import (
    CANONICAL_ALGORITHM_VERSION,
    CANONICAL_AXES,
    CANONICAL_OBSM_KEY,
    CANONICAL_SCHEMA_VERSION,
    SPATIAL_COORDINATES_KEY,
    build_canonical_cache_update_payload,
    build_canonical_metadata,
    build_canonical_region_binding,
    build_canonical_source_signature,
    canonical_metadata_to_storage,
    inspect_canonical_cache,
    parse_canonical_metadata,
    validate_canonical_payload,
)

__all__ = [
    "CANONICAL_ALGORITHM_VERSION",
    "CANONICAL_AXES",
    "CANONICAL_OBSM_KEY",
    "CANONICAL_SCHEMA_VERSION",
    "SPATIAL_COORDINATES_KEY",
    "CanonicalCacheMismatch",
    "CanonicalCacheReport",
    "CanonicalCacheState",
    "CanonicalCacheUpdateAction",
    "CanonicalCacheUpdatePayload",
    "CanonicalCacheUpdateResult",
    "CanonicalCentersResult",
    "CanonicalMetadata",
    "CanonicalMismatchCode",
    "CanonicalRegionBinding",
    "CanonicalRegionMetadata",
    "CanonicalSourceSignature",
    "build_canonical_cache_update_payload",
    "build_canonical_metadata",
    "build_canonical_region_binding",
    "build_canonical_source_signature",
    "build_instance_set_digest",
    "calculate_canonical_centers",
    "canonical_metadata_to_storage",
    "inspect_canonical_cache",
    "parse_canonical_metadata",
    "read_canonical_centers_from_cache",
    "validate_canonical_payload",
]
