method: "cellpose"
_target_: napari_sparrow.widgets._segment_widget.create_cellpose_method
min_size: 80
flow_threshold: 0.8
diameter:  50
cellprob_threshold: -2
model_type: "nuclei"
channels: [0, 0]
small_size_vis: [3000, 6000, 5000, 9000]
masks: False
adata: False
library_id: 'melanoma'