method: "baysor"
adata_dir: ${paths.data_dir}/resolve_liver/baysor
data: ${segmentation.adata_dir}/20272_slide1_A1-1/
small_size_vis: [3000, 6000, 5000, 9000]
masks: False
adata: True
channels: [0, 0]
library_id: 'melanoma'