name: Run tests

on:
  workflow_dispatch:

# skip automatic testing
  #push:
  #  branches:
  #    - main

  #pull_request:
  #  branches:
  #    - main

  #  paths:
  #    - "src/harpy/**"
  #    - ".github/workflows/run_tests.yml"

env:
  CACHE_NUMBER: 1 # increase to reset cache manually

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # these libraries enable testing on Qt on linux
      - uses: tlambert03/setup-qt-libs@v1

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: harpy
          use-mamba: true
          python-version: ${{ matrix.python-version }}

      - name: Set cache environment variables
        shell: bash -l {0}
        run: |
          CONDA_PREFIX=$(python -c "import sys; print(sys.prefix)")
          echo "$CONDA_PREFIX"
          echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV

      #- name: Set cache date
      #  run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.CONDA_PREFIX }}
          key: conda-env-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n harpy -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      # this runs the platform-specific tests declared in tox.ini
      - name: Test with tox
        shell: bash -l {0}
        run: |
          conda activate harpy
          pip install -e '.[testing]'
          pytest --ignore=src/harpy/_tests/test_widget.py --color=yes --cov=dummy --cov-config=pyproject.toml --cov-report=xml --cov-report=term-missing

        env:
          PLATFORM: ${{ matrix.os }}

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml
